from multifractal_analysis.spectral import spectral_analysis
from multifractal_analysis.double_trace_moment import dtm_analysis
from multifractal_analysis.trace_moment import tm_analysis
from multifractal_analysis.fractal_dimension import fractal_dimension_analysis
