[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name="analysis_toolbox",
version="0.0.2",
description="Simple tools for analysing distrometer data.",
dynamic = ["version"],
authors = [
  {name = "Marcio Matheus", email="marciomsantoss@gmail.com"}
],
maintainers = [
  {name = "Marcio Matheus", email="marciomsantoss@gmail.com"}
],
requires-python = ">= 3.11",
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
],

[project.urls]
Repository = "https://github.com/marcinmss/rain_analysis_toolbox",
